package github

import (
	"context"

	"github.com/raystack/optimus/client/extension/factory"
	"github.com/raystack/optimus/client/extension/model"
)

const provider = "github"

// Client defines github client
type Client struct{}

// DownloadRelease downloads a release based on the API path
func (*Client) DownloadRelease(ctx context.Context, apiPath string) (*model.RepositoryRelease, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DownloadAsset downloads github asset based on the asset api path.
// Currently, it can only download asset from publicly available repository.
// `apiPath` follows prefix [https://api.github.com/repos], which can be
// generated by this provider parser. For more information,
// check [this](https://docs.github.com/en/rest/releases/releases) documentation.
func (c *Client) DownloadAsset(ctx context.Context, apiPath string) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (*Client) downloadAsset(ctx context.Context, url string) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *Client) getAssetURL(release *model.RepositoryRelease) (string, error) {
	_ = "STUB: not implemented"
	return "", nil
}

func (*Client) getDistSuffix() string { _ = "STUB: not implemented"; return "" }

func init() { //nolint:gochecknoinits
	if err := factory.ClientRegistry.Add(provider, &Client{}); err != nil {
		panic(err)
	}
}
