// Code generated by mockery v2.10.6. DO NOT EDIT.

package mock

import "github.com/stretchr/testify/mock"

// AssetOperator is an autogenerated mock type for the AssetOperator type
type AssetOperator struct {
	mock.Mock
}

// Install provides a mock function with given fields: asset, tagName
func (_m *AssetOperator) Install(asset []byte, tagName string) error {
	_ = "STUB: not implemented"
	return nil
}

// Prepare provides a mock function with given fields: localDirPath
func (_m *AssetOperator) Prepare(localDirPath string) error { _ = "STUB: not implemented"; return nil }

// Run provides a mock function with given fields: tagName, args
func (_m *AssetOperator) Run(tagName string, args ...string) error {
	_ = "STUB: not implemented"
	return nil
}

// Uninstall provides a mock function with given fields: tagNames
func (_m *AssetOperator) Uninstall(tagNames ...string) error { _ = "STUB: not implemented"; return nil }
