// Code generated by mockery v2.10.6. DO NOT EDIT.

package mock

import (
	"context"

	"github.com/stretchr/testify/mock"

	"github.com/raystack/optimus/client/extension/model"
)

// Client is an autogenerated mock type for the Client type
type Client struct {
	mock.Mock
}

// DownloadAsset provides a mock function with given fields: _a0, _a1
func (_m *Client) DownloadAsset(_a0 context.Context, _a1 string) ([]byte, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// DownloadRelease provides a mock function with given fields: _a0, _a1
func (_m *Client) DownloadRelease(_a0 context.Context, _a1 string) (*model.RepositoryRelease, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
