// Code generated by mockery v2.10.6. DO NOT EDIT.

package mock

import (
	"github.com/stretchr/testify/mock"

	"github.com/raystack/optimus/client/extension/model"
)

// Manifester is an autogenerated mock type for the Manifester type
type Manifester struct {
	mock.Mock
}

// Flush provides a mock function with given fields: manifest, dirPath
func (_m *Manifester) Flush(manifest *model.Manifest, dirPath string) error {
	_ = "STUB: not implemented"
	return nil
}

// Load provides a mock function with given fields: dirPath
func (_m *Manifester) Load(dirPath string) (*model.Manifest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}
