// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: raystack/optimus/core/v1beta1/job_spec.proto

package optimus

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// JobSpecificationServiceClient is the client API for JobSpecificationService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type JobSpecificationServiceClient interface {
	// DeployJobSpecification schedules jobs for execution
	// returns a stream of messages which can be used to track the progress
	// of deployments. Message containing ack are status events other are progress
	// events
	// State of the world request
	DeployJobSpecification(ctx context.Context, opts ...grpc.CallOption) (JobSpecificationService_DeployJobSpecificationClient, error)
	// JobInspect return a new jobSpec for a namespace which belongs to a project
	JobInspect(ctx context.Context, in *JobInspectRequest, opts ...grpc.CallOption) (*JobInspectResponse, error)
	// CreateJobSpecification registers a new job for a namespace which belongs to a project
	CreateJobSpecification(ctx context.Context, in *CreateJobSpecificationRequest, opts ...grpc.CallOption) (*CreateJobSpecificationResponse, error)
	// AddJobSpecification registers new jobs for a namespace which belongs to the given project
	AddJobSpecifications(ctx context.Context, in *AddJobSpecificationsRequest, opts ...grpc.CallOption) (*AddJobSpecificationsResponse, error)
	// UpdateJobSpecifications modify jobs for a namespace which belongs to the given project
	UpdateJobSpecifications(ctx context.Context, in *UpdateJobSpecificationsRequest, opts ...grpc.CallOption) (*UpdateJobSpecificationsResponse, error)
	// GetJobSpecification reads a provided job spec of a namespace
	GetJobSpecification(ctx context.Context, in *GetJobSpecificationRequest, opts ...grpc.CallOption) (*GetJobSpecificationResponse, error)
	// GetJobSpecifications read a job spec for provided filters
	GetJobSpecifications(ctx context.Context, in *GetJobSpecificationsRequest, opts ...grpc.CallOption) (*GetJobSpecificationsResponse, error)
	// DeleteJobSpecification deletes a job spec of a namespace
	DeleteJobSpecification(ctx context.Context, in *DeleteJobSpecificationRequest, opts ...grpc.CallOption) (*DeleteJobSpecificationResponse, error)
	// ChangeJobNamespace move a job spec from one namespace to another
	ChangeJobNamespace(ctx context.Context, in *ChangeJobNamespaceRequest, opts ...grpc.CallOption) (*ChangeJobNamespaceResponse, error)
	// ListJobSpecification returns list of jobs created in a project
	ListJobSpecification(ctx context.Context, in *ListJobSpecificationRequest, opts ...grpc.CallOption) (*ListJobSpecificationResponse, error)
	// CheckJobSpecification checks if a job specification is valid
	CheckJobSpecification(ctx context.Context, in *CheckJobSpecificationRequest, opts ...grpc.CallOption) (*CheckJobSpecificationResponse, error)
	// CheckJobSpecifications checks if the job specifications are valid
	CheckJobSpecifications(ctx context.Context, in *CheckJobSpecificationsRequest, opts ...grpc.CallOption) (JobSpecificationService_CheckJobSpecificationsClient, error)
	// RefreshJobs do redeployment using the current persisted state.
	// It will returns a stream of messages which can be used to track the progress.
	RefreshJobs(ctx context.Context, in *RefreshJobsRequest, opts ...grpc.CallOption) (JobSpecificationService_RefreshJobsClient, error)
	// GetDeployJobsStatus check status of job deployment.
	// It will returns status of the job deployment and the failure details.
	GetDeployJobsStatus(ctx context.Context, in *GetDeployJobsStatusRequest, opts ...grpc.CallOption) (*GetDeployJobsStatusResponse, error)
	// ReplaceAllJobSpecifications replaces all jobs in server for a given tenant
	ReplaceAllJobSpecifications(ctx context.Context, opts ...grpc.CallOption) (JobSpecificationService_ReplaceAllJobSpecificationsClient, error)
	// GetJobTask provides task details specific to plugin used in a job
	GetJobTask(ctx context.Context, in *GetJobTaskRequest, opts ...grpc.CallOption) (*GetJobTaskResponse, error)
	// GetWindow provides the start and end dates provided a scheduled date
	// of the execution window
	GetWindow(ctx context.Context, in *GetWindowRequest, opts ...grpc.CallOption) (*GetWindowResponse, error)
	// UpdateJobState enable / disable job on scheuler
	UpdateJobsState(ctx context.Context, in *UpdateJobsStateRequest, opts ...grpc.CallOption) (*UpdateJobsStateResponse, error)
	// SyncJobsState enable / disable job on scheuler
	SyncJobsState(ctx context.Context, in *SyncJobsStateRequest, opts ...grpc.CallOption) (*SyncJobsStateResponse, error)
}

type jobSpecificationServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewJobSpecificationServiceClient(cc grpc.ClientConnInterface) JobSpecificationServiceClient {
	_ = "STUB: not implemented"
	return *new(JobSpecificationServiceClient)
}

func (c *jobSpecificationServiceClient) DeployJobSpecification(ctx context.Context, opts ...grpc.CallOption) (JobSpecificationService_DeployJobSpecificationClient, error) {
	_ = "STUB: not implemented"
	return *new(JobSpecificationService_DeployJobSpecificationClient), nil
}

type JobSpecificationService_DeployJobSpecificationClient interface {
	Send(*DeployJobSpecificationRequest) error
	Recv() (*DeployJobSpecificationResponse, error)
	grpc.ClientStream
}

type jobSpecificationServiceDeployJobSpecificationClient struct {
	grpc.ClientStream
}

func (x *jobSpecificationServiceDeployJobSpecificationClient) Send(m *DeployJobSpecificationRequest) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *jobSpecificationServiceDeployJobSpecificationClient) Recv() (*DeployJobSpecificationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) JobInspect(ctx context.Context, in *JobInspectRequest, opts ...grpc.CallOption) (*JobInspectResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) CreateJobSpecification(ctx context.Context, in *CreateJobSpecificationRequest, opts ...grpc.CallOption) (*CreateJobSpecificationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) AddJobSpecifications(ctx context.Context, in *AddJobSpecificationsRequest, opts ...grpc.CallOption) (*AddJobSpecificationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) UpdateJobSpecifications(ctx context.Context, in *UpdateJobSpecificationsRequest, opts ...grpc.CallOption) (*UpdateJobSpecificationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) GetJobSpecification(ctx context.Context, in *GetJobSpecificationRequest, opts ...grpc.CallOption) (*GetJobSpecificationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) GetJobSpecifications(ctx context.Context, in *GetJobSpecificationsRequest, opts ...grpc.CallOption) (*GetJobSpecificationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) DeleteJobSpecification(ctx context.Context, in *DeleteJobSpecificationRequest, opts ...grpc.CallOption) (*DeleteJobSpecificationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) ChangeJobNamespace(ctx context.Context, in *ChangeJobNamespaceRequest, opts ...grpc.CallOption) (*ChangeJobNamespaceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) ListJobSpecification(ctx context.Context, in *ListJobSpecificationRequest, opts ...grpc.CallOption) (*ListJobSpecificationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) CheckJobSpecification(ctx context.Context, in *CheckJobSpecificationRequest, opts ...grpc.CallOption) (*CheckJobSpecificationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) CheckJobSpecifications(ctx context.Context, in *CheckJobSpecificationsRequest, opts ...grpc.CallOption) (JobSpecificationService_CheckJobSpecificationsClient, error) {
	_ = "STUB: not implemented"
	return *new(JobSpecificationService_CheckJobSpecificationsClient), nil
}

type JobSpecificationService_CheckJobSpecificationsClient interface {
	Recv() (*CheckJobSpecificationsResponse, error)
	grpc.ClientStream
}

type jobSpecificationServiceCheckJobSpecificationsClient struct {
	grpc.ClientStream
}

func (x *jobSpecificationServiceCheckJobSpecificationsClient) Recv() (*CheckJobSpecificationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) RefreshJobs(ctx context.Context, in *RefreshJobsRequest, opts ...grpc.CallOption) (JobSpecificationService_RefreshJobsClient, error) {
	_ = "STUB: not implemented"
	return *new(JobSpecificationService_RefreshJobsClient), nil
}

type JobSpecificationService_RefreshJobsClient interface {
	Recv() (*RefreshJobsResponse, error)
	grpc.ClientStream
}

type jobSpecificationServiceRefreshJobsClient struct {
	grpc.ClientStream
}

func (x *jobSpecificationServiceRefreshJobsClient) Recv() (*RefreshJobsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) GetDeployJobsStatus(ctx context.Context, in *GetDeployJobsStatusRequest, opts ...grpc.CallOption) (*GetDeployJobsStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) ReplaceAllJobSpecifications(ctx context.Context, opts ...grpc.CallOption) (JobSpecificationService_ReplaceAllJobSpecificationsClient, error) {
	_ = "STUB: not implemented"
	return *new(JobSpecificationService_ReplaceAllJobSpecificationsClient), nil
}

type JobSpecificationService_ReplaceAllJobSpecificationsClient interface {
	Send(*ReplaceAllJobSpecificationsRequest) error
	Recv() (*ReplaceAllJobSpecificationsResponse, error)
	grpc.ClientStream
}

type jobSpecificationServiceReplaceAllJobSpecificationsClient struct {
	grpc.ClientStream
}

func (x *jobSpecificationServiceReplaceAllJobSpecificationsClient) Send(m *ReplaceAllJobSpecificationsRequest) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *jobSpecificationServiceReplaceAllJobSpecificationsClient) Recv() (*ReplaceAllJobSpecificationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) GetJobTask(ctx context.Context, in *GetJobTaskRequest, opts ...grpc.CallOption) (*GetJobTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) GetWindow(ctx context.Context, in *GetWindowRequest, opts ...grpc.CallOption) (*GetWindowResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) UpdateJobsState(ctx context.Context, in *UpdateJobsStateRequest, opts ...grpc.CallOption) (*UpdateJobsStateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *jobSpecificationServiceClient) SyncJobsState(ctx context.Context, in *SyncJobsStateRequest, opts ...grpc.CallOption) (*SyncJobsStateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// JobSpecificationServiceServer is the server API for JobSpecificationService service.
// All implementations must embed UnimplementedJobSpecificationServiceServer
// for forward compatibility
type JobSpecificationServiceServer interface {
	// DeployJobSpecification schedules jobs for execution
	// returns a stream of messages which can be used to track the progress
	// of deployments. Message containing ack are status events other are progress
	// events
	// State of the world request
	DeployJobSpecification(JobSpecificationService_DeployJobSpecificationServer) error
	// JobInspect return a new jobSpec for a namespace which belongs to a project
	JobInspect(context.Context, *JobInspectRequest) (*JobInspectResponse, error)
	// CreateJobSpecification registers a new job for a namespace which belongs to a project
	CreateJobSpecification(context.Context, *CreateJobSpecificationRequest) (*CreateJobSpecificationResponse, error)
	// AddJobSpecification registers new jobs for a namespace which belongs to the given project
	AddJobSpecifications(context.Context, *AddJobSpecificationsRequest) (*AddJobSpecificationsResponse, error)
	// UpdateJobSpecifications modify jobs for a namespace which belongs to the given project
	UpdateJobSpecifications(context.Context, *UpdateJobSpecificationsRequest) (*UpdateJobSpecificationsResponse, error)
	// GetJobSpecification reads a provided job spec of a namespace
	GetJobSpecification(context.Context, *GetJobSpecificationRequest) (*GetJobSpecificationResponse, error)
	// GetJobSpecifications read a job spec for provided filters
	GetJobSpecifications(context.Context, *GetJobSpecificationsRequest) (*GetJobSpecificationsResponse, error)
	// DeleteJobSpecification deletes a job spec of a namespace
	DeleteJobSpecification(context.Context, *DeleteJobSpecificationRequest) (*DeleteJobSpecificationResponse, error)
	// ChangeJobNamespace move a job spec from one namespace to another
	ChangeJobNamespace(context.Context, *ChangeJobNamespaceRequest) (*ChangeJobNamespaceResponse, error)
	// ListJobSpecification returns list of jobs created in a project
	ListJobSpecification(context.Context, *ListJobSpecificationRequest) (*ListJobSpecificationResponse, error)
	// CheckJobSpecification checks if a job specification is valid
	CheckJobSpecification(context.Context, *CheckJobSpecificationRequest) (*CheckJobSpecificationResponse, error)
	// CheckJobSpecifications checks if the job specifications are valid
	CheckJobSpecifications(*CheckJobSpecificationsRequest, JobSpecificationService_CheckJobSpecificationsServer) error
	// RefreshJobs do redeployment using the current persisted state.
	// It will returns a stream of messages which can be used to track the progress.
	RefreshJobs(*RefreshJobsRequest, JobSpecificationService_RefreshJobsServer) error
	// GetDeployJobsStatus check status of job deployment.
	// It will returns status of the job deployment and the failure details.
	GetDeployJobsStatus(context.Context, *GetDeployJobsStatusRequest) (*GetDeployJobsStatusResponse, error)
	// ReplaceAllJobSpecifications replaces all jobs in server for a given tenant
	ReplaceAllJobSpecifications(JobSpecificationService_ReplaceAllJobSpecificationsServer) error
	// GetJobTask provides task details specific to plugin used in a job
	GetJobTask(context.Context, *GetJobTaskRequest) (*GetJobTaskResponse, error)
	// GetWindow provides the start and end dates provided a scheduled date
	// of the execution window
	GetWindow(context.Context, *GetWindowRequest) (*GetWindowResponse, error)
	// UpdateJobState enable / disable job on scheuler
	UpdateJobsState(context.Context, *UpdateJobsStateRequest) (*UpdateJobsStateResponse, error)
	// SyncJobsState enable / disable job on scheuler
	SyncJobsState(context.Context, *SyncJobsStateRequest) (*SyncJobsStateResponse, error)
	mustEmbedUnimplementedJobSpecificationServiceServer()
}

// UnimplementedJobSpecificationServiceServer must be embedded to have forward compatible implementations.
type UnimplementedJobSpecificationServiceServer struct {
}

func (UnimplementedJobSpecificationServiceServer) DeployJobSpecification(JobSpecificationService_DeployJobSpecificationServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedJobSpecificationServiceServer) JobInspect(context.Context, *JobInspectRequest) (*JobInspectResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) CreateJobSpecification(context.Context, *CreateJobSpecificationRequest) (*CreateJobSpecificationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) AddJobSpecifications(context.Context, *AddJobSpecificationsRequest) (*AddJobSpecificationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) UpdateJobSpecifications(context.Context, *UpdateJobSpecificationsRequest) (*UpdateJobSpecificationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) GetJobSpecification(context.Context, *GetJobSpecificationRequest) (*GetJobSpecificationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) GetJobSpecifications(context.Context, *GetJobSpecificationsRequest) (*GetJobSpecificationsResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) DeleteJobSpecification(context.Context, *DeleteJobSpecificationRequest) (*DeleteJobSpecificationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) ChangeJobNamespace(context.Context, *ChangeJobNamespaceRequest) (*ChangeJobNamespaceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) ListJobSpecification(context.Context, *ListJobSpecificationRequest) (*ListJobSpecificationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) CheckJobSpecification(context.Context, *CheckJobSpecificationRequest) (*CheckJobSpecificationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) CheckJobSpecifications(*CheckJobSpecificationsRequest, JobSpecificationService_CheckJobSpecificationsServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedJobSpecificationServiceServer) RefreshJobs(*RefreshJobsRequest, JobSpecificationService_RefreshJobsServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedJobSpecificationServiceServer) GetDeployJobsStatus(context.Context, *GetDeployJobsStatusRequest) (*GetDeployJobsStatusResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) ReplaceAllJobSpecifications(JobSpecificationService_ReplaceAllJobSpecificationsServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedJobSpecificationServiceServer) GetJobTask(context.Context, *GetJobTaskRequest) (*GetJobTaskResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) GetWindow(context.Context, *GetWindowRequest) (*GetWindowResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) UpdateJobsState(context.Context, *UpdateJobsStateRequest) (*UpdateJobsStateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) SyncJobsState(context.Context, *SyncJobsStateRequest) (*SyncJobsStateResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedJobSpecificationServiceServer) mustEmbedUnimplementedJobSpecificationServiceServer() {
	_ = "STUB: not implemented"

	// UnsafeJobSpecificationServiceServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to JobSpecificationServiceServer will
	// result in compilation errors.
	return
}

type UnsafeJobSpecificationServiceServer interface {
	mustEmbedUnimplementedJobSpecificationServiceServer()
}

func RegisterJobSpecificationServiceServer(s grpc.ServiceRegistrar, srv JobSpecificationServiceServer) {
	_ = "STUB: not implemented"
	return
}

func _JobSpecificationService_DeployJobSpecification_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type JobSpecificationService_DeployJobSpecificationServer interface {
	Send(*DeployJobSpecificationResponse) error
	Recv() (*DeployJobSpecificationRequest, error)
	grpc.ServerStream
}

type jobSpecificationServiceDeployJobSpecificationServer struct {
	grpc.ServerStream
}

func (x *jobSpecificationServiceDeployJobSpecificationServer) Send(m *DeployJobSpecificationResponse) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *jobSpecificationServiceDeployJobSpecificationServer) Recv() (*DeployJobSpecificationRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_JobInspect_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_CreateJobSpecification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_AddJobSpecifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_UpdateJobSpecifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_GetJobSpecification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_GetJobSpecifications_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_DeleteJobSpecification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_ChangeJobNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_ListJobSpecification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_CheckJobSpecification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_CheckJobSpecifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type JobSpecificationService_CheckJobSpecificationsServer interface {
	Send(*CheckJobSpecificationsResponse) error
	grpc.ServerStream
}

type jobSpecificationServiceCheckJobSpecificationsServer struct {
	grpc.ServerStream
}

func (x *jobSpecificationServiceCheckJobSpecificationsServer) Send(m *CheckJobSpecificationsResponse) error {
	_ = "STUB: not implemented"
	return nil
}

func _JobSpecificationService_RefreshJobs_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type JobSpecificationService_RefreshJobsServer interface {
	Send(*RefreshJobsResponse) error
	grpc.ServerStream
}

type jobSpecificationServiceRefreshJobsServer struct {
	grpc.ServerStream
}

func (x *jobSpecificationServiceRefreshJobsServer) Send(m *RefreshJobsResponse) error {
	_ = "STUB: not implemented"
	return nil
}

func _JobSpecificationService_GetDeployJobsStatus_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_ReplaceAllJobSpecifications_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type JobSpecificationService_ReplaceAllJobSpecificationsServer interface {
	Send(*ReplaceAllJobSpecificationsResponse) error
	Recv() (*ReplaceAllJobSpecificationsRequest, error)
	grpc.ServerStream
}

type jobSpecificationServiceReplaceAllJobSpecificationsServer struct {
	grpc.ServerStream
}

func (x *jobSpecificationServiceReplaceAllJobSpecificationsServer) Send(m *ReplaceAllJobSpecificationsResponse) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *jobSpecificationServiceReplaceAllJobSpecificationsServer) Recv() (*ReplaceAllJobSpecificationsRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_GetJobTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_GetWindow_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_UpdateJobsState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _JobSpecificationService_SyncJobsState_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// JobSpecificationService_ServiceDesc is the grpc.ServiceDesc for JobSpecificationService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var JobSpecificationService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raystack.optimus.core.v1beta1.JobSpecificationService",
	HandlerType: (*JobSpecificationServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "JobInspect",
			Handler:    _JobSpecificationService_JobInspect_Handler,
		},
		{
			MethodName: "CreateJobSpecification",
			Handler:    _JobSpecificationService_CreateJobSpecification_Handler,
		},
		{
			MethodName: "AddJobSpecifications",
			Handler:    _JobSpecificationService_AddJobSpecifications_Handler,
		},
		{
			MethodName: "UpdateJobSpecifications",
			Handler:    _JobSpecificationService_UpdateJobSpecifications_Handler,
		},
		{
			MethodName: "GetJobSpecification",
			Handler:    _JobSpecificationService_GetJobSpecification_Handler,
		},
		{
			MethodName: "GetJobSpecifications",
			Handler:    _JobSpecificationService_GetJobSpecifications_Handler,
		},
		{
			MethodName: "DeleteJobSpecification",
			Handler:    _JobSpecificationService_DeleteJobSpecification_Handler,
		},
		{
			MethodName: "ChangeJobNamespace",
			Handler:    _JobSpecificationService_ChangeJobNamespace_Handler,
		},
		{
			MethodName: "ListJobSpecification",
			Handler:    _JobSpecificationService_ListJobSpecification_Handler,
		},
		{
			MethodName: "CheckJobSpecification",
			Handler:    _JobSpecificationService_CheckJobSpecification_Handler,
		},
		{
			MethodName: "GetDeployJobsStatus",
			Handler:    _JobSpecificationService_GetDeployJobsStatus_Handler,
		},
		{
			MethodName: "GetJobTask",
			Handler:    _JobSpecificationService_GetJobTask_Handler,
		},
		{
			MethodName: "GetWindow",
			Handler:    _JobSpecificationService_GetWindow_Handler,
		},
		{
			MethodName: "UpdateJobsState",
			Handler:    _JobSpecificationService_UpdateJobsState_Handler,
		},
		{
			MethodName: "SyncJobsState",
			Handler:    _JobSpecificationService_SyncJobsState_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DeployJobSpecification",
			Handler:       _JobSpecificationService_DeployJobSpecification_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
		{
			StreamName:    "CheckJobSpecifications",
			Handler:       _JobSpecificationService_CheckJobSpecifications_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "RefreshJobs",
			Handler:       _JobSpecificationService_RefreshJobs_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "ReplaceAllJobSpecifications",
			Handler:       _JobSpecificationService_ReplaceAllJobSpecifications_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "raystack/optimus/core/v1beta1/job_spec.proto",
}
