// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: raystack/optimus/core/v1beta1/namespace.proto

/*
Package optimus is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package optimus

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_NamespaceService_RegisterProjectNamespace_0(ctx context.Context, marshaler runtime.Marshaler, client NamespaceServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_NamespaceService_RegisterProjectNamespace_0(ctx context.Context, marshaler runtime.Marshaler, server NamespaceServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_NamespaceService_ListProjectNamespaces_0(ctx context.Context, marshaler runtime.Marshaler, client NamespaceServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_NamespaceService_ListProjectNamespaces_0(ctx context.Context, marshaler runtime.Marshaler, server NamespaceServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_NamespaceService_GetNamespace_0(ctx context.Context, marshaler runtime.Marshaler, client NamespaceServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_NamespaceService_GetNamespace_0(ctx context.Context, marshaler runtime.Marshaler, server NamespaceServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

// RegisterNamespaceServiceHandlerServer registers the http handlers for service NamespaceService to "mux".
// UnaryRPC     :call NamespaceServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterNamespaceServiceHandlerFromEndpoint instead.
func RegisterNamespaceServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server NamespaceServiceServer) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterNamespaceServiceHandlerFromEndpoint is same as RegisterNamespaceServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterNamespaceServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// RegisterNamespaceServiceHandler registers the http handlers for service NamespaceService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterNamespaceServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterNamespaceServiceHandlerClient registers the http handlers for service NamespaceService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "NamespaceServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "NamespaceServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "NamespaceServiceClient" to call the correct interceptors.
func RegisterNamespaceServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client NamespaceServiceClient) error {
	_ = "STUB: not implemented"
	return nil
}

var (
	pattern_NamespaceService_RegisterProjectNamespace_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2, 2, 3}, []string{"v1beta1", "project", "project_name", "namespace"}, ""))

	pattern_NamespaceService_ListProjectNamespaces_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2, 2, 3}, []string{"v1beta1", "project", "project_name", "namespace"}, ""))

	pattern_NamespaceService_GetNamespace_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2, 2, 3, 1, 0, 4, 1, 5, 4}, []string{"v1beta1", "project", "project_name", "namespace", "namespace_name"}, ""))
)

var (
	forward_NamespaceService_RegisterProjectNamespace_0 = runtime.ForwardResponseMessage

	forward_NamespaceService_ListProjectNamespaces_0 = runtime.ForwardResponseMessage

	forward_NamespaceService_GetNamespace_0 = runtime.ForwardResponseMessage
)
