// Code generated by protoc-gen-grpc-gateway. DO NOT EDIT.
// source: raystack/optimus/core/v1beta1/replay.proto

/*
Package optimus is a reverse proxy.

It translates gRPC into RESTful JSON APIs.
*/
package optimus

import (
	"context"
	"io"
	"net/http"

	"github.com/grpc-ecosystem/grpc-gateway/v2/runtime"
	"github.com/grpc-ecosystem/grpc-gateway/v2/utilities"
	"google.golang.org/grpc"
	"google.golang.org/grpc/codes"
	"google.golang.org/grpc/metadata"
	"google.golang.org/grpc/status"
	"google.golang.org/protobuf/proto"
)

// Suppress "imported and not used" errors
var _ codes.Code
var _ io.Reader
var _ status.Status
var _ = runtime.String
var _ = utilities.NewDoubleArray
var _ = metadata.Join

func request_ReplayService_Replay_0(ctx context.Context, marshaler runtime.Marshaler, client ReplayServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_ReplayService_Replay_0(ctx context.Context, marshaler runtime.Marshaler, server ReplayServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_ReplayService_ReplayDryRun_0(ctx context.Context, marshaler runtime.Marshaler, client ReplayServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_ReplayService_ReplayDryRun_0(ctx context.Context, marshaler runtime.Marshaler, server ReplayServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_ReplayService_ListReplay_0(ctx context.Context, marshaler runtime.Marshaler, client ReplayServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_ReplayService_ListReplay_0(ctx context.Context, marshaler runtime.Marshaler, server ReplayServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func request_ReplayService_GetReplay_0(ctx context.Context, marshaler runtime.Marshaler, client ReplayServiceClient, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

func local_request_ReplayService_GetReplay_0(ctx context.Context, marshaler runtime.Marshaler, server ReplayServiceServer, req *http.Request, pathParams map[string]string) (proto.Message, runtime.ServerMetadata, error) {
	_ = "STUB: not implemented"
	return *new(proto.Message), *new(runtime.ServerMetadata), nil
}

// RegisterReplayServiceHandlerServer registers the http handlers for service ReplayService to "mux".
// UnaryRPC     :call ReplayServiceServer directly.
// StreamingRPC :currently unsupported pending https://github.com/grpc/grpc-go/issues/906.
// Note that using this registration option will cause many gRPC library features to stop working. Consider using RegisterReplayServiceHandlerFromEndpoint instead.
func RegisterReplayServiceHandlerServer(ctx context.Context, mux *runtime.ServeMux, server ReplayServiceServer) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterReplayServiceHandlerFromEndpoint is same as RegisterReplayServiceHandler but
// automatically dials to "endpoint" and closes the connection when "ctx" gets done.
func RegisterReplayServiceHandlerFromEndpoint(ctx context.Context, mux *runtime.ServeMux, endpoint string, opts []grpc.DialOption) (err error) {
	_ = "STUB: not implemented"
	return nil
}

// RegisterReplayServiceHandler registers the http handlers for service ReplayService to "mux".
// The handlers forward requests to the grpc endpoint over "conn".
func RegisterReplayServiceHandler(ctx context.Context, mux *runtime.ServeMux, conn *grpc.ClientConn) error {
	_ = "STUB: not implemented"
	return nil
}

// RegisterReplayServiceHandlerClient registers the http handlers for service ReplayService
// to "mux". The handlers forward requests to the grpc endpoint over the given implementation of "ReplayServiceClient".
// Note: the gRPC framework executes interceptors within the gRPC handler. If the passed in "ReplayServiceClient"
// doesn't go through the normal gRPC flow (creating a gRPC client etc.) then it will be up to the passed in
// "ReplayServiceClient" to call the correct interceptors.
func RegisterReplayServiceHandlerClient(ctx context.Context, mux *runtime.ServeMux, client ReplayServiceClient) error {
	_ = "STUB: not implemented"
	return nil
}

var (
	pattern_ReplayService_Replay_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2, 2, 3}, []string{"v1beta1", "project", "project_name", "replay"}, ""))

	pattern_ReplayService_ReplayDryRun_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2, 2, 3}, []string{"v1beta1", "project", "project_name", "replay-dry-run"}, ""))

	pattern_ReplayService_ListReplay_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2, 2, 3}, []string{"v1beta1", "project", "project_name", "replay"}, ""))

	pattern_ReplayService_GetReplay_0 = runtime.MustPattern(runtime.NewPattern(1, []int{2, 0, 2, 1, 1, 0, 4, 1, 5, 2, 2, 3, 1, 0, 4, 1, 5, 4}, []string{"v1beta1", "project", "project_name", "replay", "replay_id"}, ""))
)

var (
	forward_ReplayService_Replay_0 = runtime.ForwardResponseMessage

	forward_ReplayService_ReplayDryRun_0 = runtime.ForwardResponseMessage

	forward_ReplayService_ListReplay_0 = runtime.ForwardResponseMessage

	forward_ReplayService_GetReplay_0 = runtime.ForwardResponseMessage
)
