// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.2.0
// - protoc             (unknown)
// source: raystack/optimus/core/v1beta1/resource.proto

package optimus

import (
	context "context"

	grpc "google.golang.org/grpc"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

// ResourceServiceClient is the client API for ResourceService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type ResourceServiceClient interface {
	// DeployResourceSpecification migrate all resource specifications of a datastore in project
	// State of the world request
	DeployResourceSpecification(ctx context.Context, opts ...grpc.CallOption) (ResourceService_DeployResourceSpecificationClient, error)
	// ListResourceSpecification lists all resource specifications of a datastore in project
	ListResourceSpecification(ctx context.Context, in *ListResourceSpecificationRequest, opts ...grpc.CallOption) (*ListResourceSpecificationResponse, error)
	// Database CRUD
	// CreateResource registers a new resource of a namespace which belongs to a project
	CreateResource(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*CreateResourceResponse, error)
	// ReadResource reads a provided resource spec of a namespace
	ReadResource(ctx context.Context, in *ReadResourceRequest, opts ...grpc.CallOption) (*ReadResourceResponse, error)
	// UpdateResource updates a resource specification of a datastore in project
	UpdateResource(ctx context.Context, in *UpdateResourceRequest, opts ...grpc.CallOption) (*UpdateResourceResponse, error)
	// ChangeJobNamespace move a job spec from one namespace to another
	ChangeResourceNamespace(ctx context.Context, in *ChangeResourceNamespaceRequest, opts ...grpc.CallOption) (*ChangeResourceNamespaceResponse, error)
	// apply a resource from optimus to datastore
	ApplyResources(ctx context.Context, in *ApplyResourcesRequest, opts ...grpc.CallOption) (*ApplyResourcesResponse, error)
}

type resourceServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewResourceServiceClient(cc grpc.ClientConnInterface) ResourceServiceClient {
	_ = "STUB: not implemented"
	return *new(ResourceServiceClient)
}

func (c *resourceServiceClient) DeployResourceSpecification(ctx context.Context, opts ...grpc.CallOption) (ResourceService_DeployResourceSpecificationClient, error) {
	_ = "STUB: not implemented"
	return *new(ResourceService_DeployResourceSpecificationClient), nil
}

type ResourceService_DeployResourceSpecificationClient interface {
	Send(*DeployResourceSpecificationRequest) error
	Recv() (*DeployResourceSpecificationResponse, error)
	grpc.ClientStream
}

type resourceServiceDeployResourceSpecificationClient struct {
	grpc.ClientStream
}

func (x *resourceServiceDeployResourceSpecificationClient) Send(m *DeployResourceSpecificationRequest) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *resourceServiceDeployResourceSpecificationClient) Recv() (*DeployResourceSpecificationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *resourceServiceClient) ListResourceSpecification(ctx context.Context, in *ListResourceSpecificationRequest, opts ...grpc.CallOption) (*ListResourceSpecificationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *resourceServiceClient) CreateResource(ctx context.Context, in *CreateResourceRequest, opts ...grpc.CallOption) (*CreateResourceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *resourceServiceClient) ReadResource(ctx context.Context, in *ReadResourceRequest, opts ...grpc.CallOption) (*ReadResourceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *resourceServiceClient) UpdateResource(ctx context.Context, in *UpdateResourceRequest, opts ...grpc.CallOption) (*UpdateResourceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *resourceServiceClient) ChangeResourceNamespace(ctx context.Context, in *ChangeResourceNamespaceRequest, opts ...grpc.CallOption) (*ChangeResourceNamespaceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (c *resourceServiceClient) ApplyResources(ctx context.Context, in *ApplyResourcesRequest, opts ...grpc.CallOption) (*ApplyResourcesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResourceServiceServer is the server API for ResourceService service.
// All implementations must embed UnimplementedResourceServiceServer
// for forward compatibility
type ResourceServiceServer interface {
	// DeployResourceSpecification migrate all resource specifications of a datastore in project
	// State of the world request
	DeployResourceSpecification(ResourceService_DeployResourceSpecificationServer) error
	// ListResourceSpecification lists all resource specifications of a datastore in project
	ListResourceSpecification(context.Context, *ListResourceSpecificationRequest) (*ListResourceSpecificationResponse, error)
	// Database CRUD
	// CreateResource registers a new resource of a namespace which belongs to a project
	CreateResource(context.Context, *CreateResourceRequest) (*CreateResourceResponse, error)
	// ReadResource reads a provided resource spec of a namespace
	ReadResource(context.Context, *ReadResourceRequest) (*ReadResourceResponse, error)
	// UpdateResource updates a resource specification of a datastore in project
	UpdateResource(context.Context, *UpdateResourceRequest) (*UpdateResourceResponse, error)
	// ChangeJobNamespace move a job spec from one namespace to another
	ChangeResourceNamespace(context.Context, *ChangeResourceNamespaceRequest) (*ChangeResourceNamespaceResponse, error)
	// apply a resource from optimus to datastore
	ApplyResources(context.Context, *ApplyResourcesRequest) (*ApplyResourcesResponse, error)
	mustEmbedUnimplementedResourceServiceServer()
}

// UnimplementedResourceServiceServer must be embedded to have forward compatible implementations.
type UnimplementedResourceServiceServer struct {
}

func (UnimplementedResourceServiceServer) DeployResourceSpecification(ResourceService_DeployResourceSpecificationServer) error {
	_ = "STUB: not implemented"
	return nil
}

func (UnimplementedResourceServiceServer) ListResourceSpecification(context.Context, *ListResourceSpecificationRequest) (*ListResourceSpecificationResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedResourceServiceServer) CreateResource(context.Context, *CreateResourceRequest) (*CreateResourceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedResourceServiceServer) ReadResource(context.Context, *ReadResourceRequest) (*ReadResourceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedResourceServiceServer) UpdateResource(context.Context, *UpdateResourceRequest) (*UpdateResourceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedResourceServiceServer) ChangeResourceNamespace(context.Context, *ChangeResourceNamespaceRequest) (*ChangeResourceNamespaceResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedResourceServiceServer) ApplyResources(context.Context, *ApplyResourcesRequest) (*ApplyResourcesResponse, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func (UnimplementedResourceServiceServer) mustEmbedUnimplementedResourceServiceServer() {
	_ = "STUB: not implemented"

	// UnsafeResourceServiceServer may be embedded to opt out of forward compatibility for this service.
	// Use of this interface is not recommended, as added methods to ResourceServiceServer will
	// result in compilation errors.
	return
}

type UnsafeResourceServiceServer interface {
	mustEmbedUnimplementedResourceServiceServer()
}

func RegisterResourceServiceServer(s grpc.ServiceRegistrar, srv ResourceServiceServer) {
	_ = "STUB: not implemented"
	return
}

func _ResourceService_DeployResourceSpecification_Handler(srv interface{}, stream grpc.ServerStream) error {
	_ = "STUB: not implemented"
	return nil
}

type ResourceService_DeployResourceSpecificationServer interface {
	Send(*DeployResourceSpecificationResponse) error
	Recv() (*DeployResourceSpecificationRequest, error)
	grpc.ServerStream
}

type resourceServiceDeployResourceSpecificationServer struct {
	grpc.ServerStream
}

func (x *resourceServiceDeployResourceSpecificationServer) Send(m *DeployResourceSpecificationResponse) error {
	_ = "STUB: not implemented"
	return nil
}

func (x *resourceServiceDeployResourceSpecificationServer) Recv() (*DeployResourceSpecificationRequest, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ResourceService_ListResourceSpecification_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ResourceService_CreateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ResourceService_ReadResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ResourceService_UpdateResource_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ResourceService_ChangeResourceNamespace_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

func _ResourceService_ApplyResources_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	_ = "STUB: not implemented"
	return nil, nil
}

// ResourceService_ServiceDesc is the grpc.ServiceDesc for ResourceService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var ResourceService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "raystack.optimus.core.v1beta1.ResourceService",
	HandlerType: (*ResourceServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ListResourceSpecification",
			Handler:    _ResourceService_ListResourceSpecification_Handler,
		},
		{
			MethodName: "CreateResource",
			Handler:    _ResourceService_CreateResource_Handler,
		},
		{
			MethodName: "ReadResource",
			Handler:    _ResourceService_ReadResource_Handler,
		},
		{
			MethodName: "UpdateResource",
			Handler:    _ResourceService_UpdateResource_Handler,
		},
		{
			MethodName: "ChangeResourceNamespace",
			Handler:    _ResourceService_ChangeResourceNamespace_Handler,
		},
		{
			MethodName: "ApplyResources",
			Handler:    _ResourceService_ApplyResources_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "DeployResourceSpecification",
			Handler:       _ResourceService_DeployResourceSpecification_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "raystack/optimus/core/v1beta1/resource.proto",
}
